[package]
name = "framesurgeon"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/josefc12/druid.git" }
im = "15.1.0"
image = "0.25.1"